sudo: false
language: node_js
node_js:
  - "4"
  - "5"
  - "6"
  - "7"
  - "8"
  - "9"
  - "10"
  - "11"
  - "12"
before_install:
before_script: grunt build
notifications:
  email:
    - snowyu.lee@gmail.com

